#ifndef LIBYT_PROJECT_INCLUDE_YT_TYPE_ARRAY_H_
#define LIBYT_PROJECT_INCLUDE_YT_TYPE_ARRAY_H_

#include "yt_macro.h"

/**
 * \struct yt_array
 * \brief Data structure to store data generated by derived function or get particle
 * functions
 */
typedef struct yt_array {
  long gid;         /*!< grid id */
  long data_length; /*!< length of the data pointer */
  void* data_ptr;   /*!< data pointer */

#ifdef __cplusplus
  yt_array() {
    gid = LNG_UNDEFINED;
    data_length = 0;
    data_ptr = nullptr;
  }
#endif  // #ifdef __cplusplus

} yt_array;

#endif  // LIBYT_PROJECT_INCLUDE_YT_TYPE_ARRAY_H_
